# Generated by Django 3.0.8 on 2020-08-20 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.TextField()),
                ('nombre', models.CharField(max_length=150)),
                ('horas', models.TimeField(auto_now_add=True)),
                ('creditos', models.IntegerField()),
                ('estado', models.TextField()),
            ],
        ),
    ]
