# Generated by Django 3.1 on 2020-08-20 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('nombrecorto', models.CharField(max_length=150)),
                ('fecha_fundacion', models.DateField()),
                ('estado', models.TextField()),
            ],
        ),
    ]
